# Do not change any other options on config files.
# Especially, we fix backbones and input resolutions for reproduction purpose.
# You may change configs for `SOLVER` when following linear scaling rule.
_BASE_: "Base-FCOS.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  FCOS:
    # ---
    # To earn extra credits, you may implement all the improvements part
    # (and should be controlled on this config file) from FCOS paper Table 3.
    # you may `FREELY CHANGE` on these configurations related to improvements.
    NORM: "GN"
    CTR_ON_REG: True
    CENTER_SAMPLE: True
    POS_RADIUS: 1.5
    LOC_LOSS_TYPE: "giou"
    NORMALIZE_REG_TARGETS: True  # fix with True
    # ---
INPUT:
  MIN_SIZE_TRAIN: (800,)
SOLVER:
  WARMUP_METHOD: "constant"
  WARMUP_FACTOR: 0.3333
  WARMUP_ITERS: 500
OUTPUT_DIR: "output/fcos/R_50_1x_improve"
