# Do not change any other options on config files.
# Especially, we fix backbones and input resolutions for reproduction purpose.
# You may change configs for `SOLVER` when following linear scaling rule.
_BASE_: "Base-FCOS.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  FCOS:
    # we provide implementation of normalization option in improvements part.
    NORMALIZE_REG_TARGETS: True  # fix with True
INPUT:
  MIN_SIZE_TRAIN: (800,)
SOLVER:
  WARMUP_METHOD: "constant"
  WARMUP_FACTOR: 0.3333
  WARMUP_ITERS: 500
OUTPUT_DIR: "output/fcos/R_50_1x"
